// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BackgroundJobDistributedLockDbContext))]
    [Migration("20240714021013_AddQueueLock")]
    partial class AddQueueLock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.QueueLocks.QueueLock", b =>
                {
                    b.Property<string>("QueueName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QueueName");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("JobName");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.HasKey("QueueName", "JobName");

                    b.ToTable("QueueLocks");
                });
#pragma warning restore 612, 618
        }
    }
}
