// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BackgroundJobDistributedLockDbContext))]
    partial class BackgroundJobDistributedLockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.JobLogs.JobLog", b =>
                {
                    b.Property<long>("JobLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobLogId"));

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppId");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("JobName");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(35)")
                        .HasDefaultValue("Started")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedTime")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.HasKey("JobLogId");

                    b.ToTable("JobLogs");
                });

            modelBuilder.Entity("Domain.Entities.QueueLocks.QueueLock", b =>
                {
                    b.Property<string>("QueueName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QueueName");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("JobName");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("GetUtcDate()");

                    b.HasKey("QueueName", "JobName");

                    b.ToTable("QueueLocks");
                });
#pragma warning restore 612, 618
        }
    }
}
